#Do not change the property name, you can change the value if needed
spring.application.name=PatientManagement
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=7189
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.datasource.url=jdbc:mysql://localhost:3306/test_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create
# Show or not log for each SQL query
spring.jpa.show-sql=true

# OAuth2 Authorization Server & Resource Server
oauth2.issuer-uri=http://localhost:7189
spring.security.oauth2.resourceserver.jwt.issuer-uri=${oauth2.issuer-uri}

oauth2.client.id=patient-client
oauth2.client.secret=patient-secret
oauth2.client.redirect-uri=http://127.0.0.1:7189/login/oauth2/code/patient-client
oauth2.client.access-token-validity-seconds=3600
oauth2.client.refresh-token-validity-seconds=86400
